let ativos = [
   {
   nome: "Tribulus Terrestris",
   foto: "https://image.tuasaude.com/media/article/tg/sm/tribulus_60744_l.jpg",
   fotodesc:"foto tribulus",
   nomeCientifico: "Puncturevine caltrop",
   dose: "A dose recomendada de Tribulus Terrestris varia de acordo com o produto e a necessidade individual, mas geralmente fica entre 250mg a 1000mg por dia. É fundamental consultar um profissional de saúde antes de iniciar o consumo, especialmente em caso de gravidez, lactação ou uso de medicamentos.",
   descricao: "O Tribulus Terrestris, uma planta medicinal tradicionalmente utilizada na medicina ayurvédica, tem sido objeto de diversos estudos que buscam elucidar seus benefícios para a saúde. Seus principais compostos bioativos, como a protodioscina, são responsáveis por muitas de suas propriedades farmacológicas. Popularmente associado ao aumento da libido e do desempenho sexual, o Tribulus Terrestris pode atuar através de diferentes mecanismos, como a modulação hormonal e o aumento da produção de óxido nítrico. Além disso, algumas pesquisas sugerem que essa planta pode oferecer benefícios para a saúde cardiovascular, fortalecer o sistema imunológico e melhorar o desempenho físico. No entanto, é importante ressaltar que os resultados dos estudos são variáveis e que mais pesquisas são necessárias para confirmar os benefícios e a segurança do uso do Tribulus Terrestris. Como ocorre com qualquer suplemento, recomenda-se consultar um profissional de saúde antes de iniciar o uso, especialmente em caso de doenças pré-existentes ou uso de outros medicamentos.O Tribulus Terrestris é uma planta medicinal bastante conhecida por suas propriedades afrodisíacas e potencial para melhorar o desempenho físico. Popularmente, é associado ao aumento da libido, da força muscular e da resistência física. No entanto, é importante ressaltar que os estudos científicos sobre seus benefícios ainda são limitados e os resultados podem variar de pessoa para pessoa.",
   linkk: "https://www.infinitypharma.com.br/wp-content/uploads/2023/06/Tribullus-Terrestris.pdf",
   tagsx: "libido vigor testosterona vitalidade",
   },
   {
   nome: "Turkesterona",
   foto: "https://blog.medicinalnaweb.com.br/wp-content/uploads/2023/04/Turkesterone-3-1-scaled.jpg",
   fotodesc:"foto turkesterona",
   nomeCientifico: "Ajuga turkestanica",
   dose: "A dosagem ideal de turkesterona ainda não está completamente estabelecida, pois as pesquisas são relativamente recentes. No entanto, a maioria dos estudos utiliza doses entre 50mg e 500mg por dia. É fundamental consultar um profissional de saúde antes de iniciar a suplementação com turkesterona, especialmente se você estiver utilizando outros medicamentos ou tiver alguma condição médica pré-existente.",
   descricao: "A turkesterona, um fitoesterol extraído da planta Ajuga turkestanica, tem ganhado destaque no mundo dos suplementos por suas potenciais propriedades anabólicas e anti-catabólicas. Estudos preliminares sugerem que a turkesterona pode atuar estimulando a síntese proteica, o que favorece o crescimento muscular e a recuperação após o exercício. Além disso, essa substância pode aumentar a força e a resistência física, tornando-a uma opção atrativa para atletas e praticantes de atividades físicas. Embora os mecanismos de ação da turkesterona ainda estejam sendo investigados, acredita-se que ela possa modular vias de sinalização celular relacionadas ao crescimento muscular e ao metabolismo energético. No entanto, é importante ressaltar que as pesquisas sobre a turkesterona ainda são limitadas e mais estudos são necessários para confirmar seus benefícios e segurança a longo prazo.",
   linkk: "https://www.infinitypharma.com.br/wp-content/uploads/2023/06/Turkesterone-1.pdf",
   tagsx: "força energia musculos desempenho recuperação",
   },
   {
   nome: "Maca Peruana",
   foto:"https://www.cnnbrasil.com.br/wp-content/uploads/sites/12/2023/07/o-que-e-para-que-serve-a-maca-peruana.jpg?w=1000",
   fotodesc:"foto maca peruana",
   nomeCientifico: "Lepidium meyenii",
   dose: "A dose recomendada de maca peruana varia de acordo com o produto e a necessidade individual, mas geralmente fica entre 1 a 3 gramas por dia. Ela pode ser consumida em pó, cápsulas ou adicionada a alimentos e bebidas. É fundamental consultar um profissional de saúde antes de iniciar o consumo, especialmente em caso de gravidez, lactação ou uso de medicamentos.",
   descricao: "A maca peruana, um tubérculo originário dos Andes peruanos, é reconhecida por seus diversos benefícios à saúde. Rica em nutrientes como vitaminas, minerais e aminoácidos, essa raiz adaptogênica é capaz de ajudar o corpo a se adaptar a diferentes tipos de estresse. Seus efeitos mais conhecidos incluem o aumento da energia e da vitalidade, a melhora da libido e da fertilidade, tanto em homens quanto em mulheres. Além disso, a maca peruana pode auxiliar no equilíbrio hormonal, especialmente durante a menopausa, e contribuir para a saúde óssea. Estudos sugerem que ela também possui propriedades antioxidantes, que ajudam a proteger as células contra os danos causados pelos radicais livres. No entanto, é importante ressaltar que os efeitos da maca peruana podem variar de pessoa para pessoa, e mais pesquisas são necessárias para compreender completamente seus mecanismos de ação.",
   linkk: "https://www.infinitypharma.com.br/wp-content/uploads/2023/06/Tribullus-Terrestris.pdf",
   tagsx:"energia vitalidade libido força",
   },
   {
   nome: "Saw Palmetto",
   foto:"https://www.coisasdaroca.com/wp-content/uploads/2019/10/Saw-Palmetto-1.jpg",
   fotodesc:"foto saw palmetto",
   nomeCientifico: "Serenoa repens",
   dose: "A dosagem recomendada de saw palmetto varia de acordo com o produto e a condição a ser tratada. Geralmente, a dose diária recomendada é de 160mg a 320mg de extrato de saw palmetto, dividida em duas ou três doses. É fundamental consultar um médico ou farmacêutico antes de iniciar o uso, especialmente se você estiver tomando outros medicamentos ou tiver alguma condição médica pré-existente.",
   descricao: "O Saw Palmetto é uma planta medicinal nativa da América do Norte, amplamente utilizada para tratar problemas da próstata, especialmente a hiperplasia benigna da próstata (BPH). Seus frutos contêm ácidos graxos e fitoesteróis que inibem a conversão da testosterona em dihidrotestosterona (DHT), um hormônio que contribui para o crescimento da próstata.",
   tagsx:"próstata saúde cabelo crescimento hormonios",
   linkk: "https://www.infinitypharma.com.br/wp-content/uploads/2023/06/Tribullus-Terrestris.pdf",
   },
   {
   nome: "Ashwagandha",
   foto: "https://www.phytoart.com.br/wp-content/uploads/2018/09/Ashwagandha.jpg",
   fotodesc: "foto da ashwandha",
   nomeCientifico: "Withania somnifera",
   dose: "A dosagem ideal de Ashwagandha pode variar de acordo com a marca, a forma de apresentação (pó, cápsulas, extrato) e a condição a ser tratada. Geralmente, a dose diária recomendada é de 300mg a 500mg de extrato de raiz de Ashwagandha, dividida em duas ou três doses. É fundamental consultar um médico ou farmacêutico antes de iniciar o uso, especialmente se você estiver tomando outros medicamentos ou tiver alguma condição médica pré-existente.",
   descricao: "A Ashwagandha, também conhecida como ginseng indiano, é uma planta medicinal utilizada há séculos na Ayurveda, a medicina tradicional indiana. Considerada um adaptógeno, ela ajuda o corpo a lidar com o estresse físico e mental, promovendo o equilíbrio interno. Seus benefícios vão além do combate ao estresse: a Ashwagandha pode melhorar a função cognitiva, aumentar os níveis de energia, fortalecer o sistema imunológico e até mesmo auxiliar no tratamento de distúrbios do sono. Além disso, algumas pesquisas sugerem que ela pode ter propriedades anti-inflamatórias e antioxidantes.",
   linkk: "https://florien.com.br/wp-content/uploads/2016/06/ASHAWAGANDA.pdf",
   tagsx: "estresse ansiedade sono força imunidade",
   },
   {
    nome: "Curcuma longa",
    foto: "https://33443.cdn.simplo7.net/static/33443/sku/cosmeticos.html-extrato-de-curcuma-longa-bio-tintura-livealoe-100ml--p-1655060388873.jpg",
    fotodesc: "foto da curcuma em um pistilo",
    nomeCientifico: "Curcuma longa",
    dose: "A dose recomendada de curcumina varia de acordo com a forma de apresentação (pó, cápsulas) e a condição a ser tratada. Geralmente, a dose diária recomendada é de 500mg a 2000mg de curcumina, dividida em duas ou três doses. Para aumentar a absorção da curcumina, recomenda-se consumi-la com alimentos ricos em gordura, como azeite de oliva. É fundamental consultar um médico ou nutricionista antes de iniciar o uso, especialmente se você estiver tomando outros medicamentos ou tiver alguma condição médica pré-existente.",
    descricao: "A cúrcuma longa, popularmente conhecida como açafrão-da-terra, é uma especiaria rica em curcumina, um composto com potentes propriedades anti-inflamatórias e antioxidantes. Utilizada há séculos na medicina tradicional, a cúrcuma tem sido estudada por seus benefícios para a saúde, incluindo a redução da inflamação, o alívio da dor articular, a proteção contra doenças neurodegenerativas e a melhora da saúde do coração. Além disso, a curcumina pode auxiliar na modulação do sistema imunológico e na prevenção de algumas doenças crônicas.",
    tagsx:"inflamação antioxidante saúde articulações bem-estar açafrão",
    linkk: "https://florien.com.br/wp-content/uploads/2016/06/A%C3%87AFR%C3%83O-1.pdf",
   },
   {
    nome: "Pfaffia paniculata",
    foto: "https://upload.wikimedia.org/wikipedia/commons/2/2a/P_glomerata-costapppr.jpg",
    fotodesc: "foto da pffafia paniculata",
    nomeCientifico: "Pfaffia paniculata",
    dose: "A dosagem recomendada de Pfaffia paniculata pode variar dependendo do produto e da condição a ser tratada. Geralmente, a dose diária recomendada é de 300mg a 1000mg de extrato seco da planta. É importante consultar um profissional de saúde antes de iniciar o uso, especialmente se você estiver grávida, amamentando ou tomando outros medicamentos.",
    descricao: "A Pfaffia paniculata, popularmente conhecida como ginseng brasileiro, é uma planta medicinal nativa da América do Sul, especialmente do Brasil, com uma longa história de uso tradicional. Rica em nutrientes e compostos bioativos, como saponinas, ela é conhecida por suas propriedades adaptógenas, auxiliando o corpo a lidar com o estresse e a fadiga. Além disso, a Pfaffia paniculata pode fortalecer o sistema imunológico, melhorar o desempenho físico e cognitivo, e contribuir para a saúde cardiovascular. Essa planta também é utilizada para auxiliar no tratamento de diversas condições, como anemia, diabetes e problemas sexuais.",
    linkk: "https://florien.com.br/wp-content/uploads/2016/06/PFAFFIA.pdf",
    tagsx:"vitalidade energia imunidade resistência bem-estar",
   },
   {
    nome: "Gymnema Sylvestre",
    foto: "https://nutritotal.com.br/pro/wp-content/uploads/2021/08/Nutritotal_PRO_13_Agosto_GYMNEMA_-SYLVESTRE-scaled.jpg",
    fotodesc: "foto das folhas de gymnema sylvestre",
    nomeCientifico: "Gymnema sylvestre",
    dose: "A dosagem ideal de Gymnema sylvestre pode variar dependendo do produto e da condição a ser tratada. Geralmente, a dose diária recomendada é de 400mg a 800mg de extrato seco da planta, dividida em duas ou três doses. É fundamental consultar um médico ou nutricionista antes de iniciar o uso, especialmente se você estiver tomando outros medicamentos ou tiver alguma condição médica pré-existente.",
    descricao: "A Gymnema sylvestre, também conhecida como destruidor de açúcar, é uma planta medicinal tradicionalmente utilizada na Índia para auxiliar no controle da diabetes. Seus compostos ativos bloqueiam temporariamente os receptores de sabor doce na língua, reduzindo o desejo por alimentos açucarados. Além disso, estudos sugerem que a Gymnema sylvestre pode estimular a produção de insulina, melhorar a sensibilidade à insulina e auxiliar na regulação dos níveis de açúcar no sangue. Essa planta também possui propriedades antioxidantes e anti-inflamatórias, contribuindo para a saúde geral do organismo.",
    linkk: "https://www.infinitypharma.com.br/wp-content/uploads/2023/06/Gymnena-Silvestre.pdf",
    tagsx: "diabetes açúcar sabor controle saúde ginema gynema gymena gimena ginmena gynmena",
  },
  {
    nome: "Spirulina",
    foto: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRXk0olR69LX9NDHmk4ymMicfkHWwL7NomX1Q&s",
    fotodesc: "foto de pó de spirulina",
    nomeCientifico: "Arthrospira platensis",
    dose: "A dosagem recomendada de spirulina pode variar dependendo do produto e do objetivo a ser alcançado. Geralmente, a dose diária recomendada é de 1 a 3 gramas, dividida em duas ou três doses. É importante iniciar com doses menores e aumentar gradualmente para avaliar a tolerância individual. Recomenda-se consultar um profissional de saúde antes de iniciar a suplementação, especialmente se você estiver grávida, amamentando ou tomando outros medicamentos.",
    descricao: "A spirulina, uma cianobactéria, é considerada um superalimento devido ao seu alto valor nutricional. Rica em proteínas de alta qualidade, vitaminas (especialmente do complexo B), minerais (ferro, magnésio) e antioxidantes, a spirulina oferece diversos benefícios para a saúde. Ela pode auxiliar na desintoxicação do organismo, fortalecer o sistema imunológico, melhorar a energia e a resistência física, além de contribuir para a saúde cardiovascular e cerebral. A spirulina também é utilizada para auxiliar no controle do peso e na redução dos níveis de colesterol.",
    linkk: "https://florien.com.br/wp-content/uploads/2023/12/SPIRULINA.pdf",
    tagsx: "energia imunidade detox vitalidade nutrição espirulina",
  },
  {
  nome: "Chá Verde",
  foto: "https://saudeemdia.com.br/wp-content/uploads/2022/08/cha-verde-2.jpg",
  fotodesc: "foto de folhas de chá verde",
  nomeCientifico: "Camellia sinensis",
  dose: "A quantidade ideal de chá verde pode variar de acordo com a tolerância individual e os objetivos de cada pessoa. Recomenda-se consumir de 2 a 4 xícaras de chá verde por dia, preferencialmente sem açúcar ou adoçantes artificiais. É importante lembrar que a cafeína presente no chá verde pode causar insônia em algumas pessoas, sendo recomendado evitar o consumo próximo à hora de dormir.",
  descricao: "O chá verde, proveniente das folhas da Camellia sinensis, é uma bebida milenar reconhecida por seus inúmeros benefícios para a saúde. Rico em antioxidantes, principalmente as catequinas, ele atua como um poderoso combatente dos radicais livres, protegendo as células do envelhecimento precoce e reduzindo o risco de diversas doenças crônicas. Além disso, o chá verde pode auxiliar na perda de peso, melhorar o desempenho cognitivo, reduzir o colesterol ruim, controlar a pressão arterial e fortalecer o sistema imunológico. Sua ação termogênica e diurética contribui para um metabolismo mais acelerado e para a eliminação de toxinas do organismo.",
  linkk: "https://www.florien.com.br/wp-content/uploads/2016/06/CHA-VERDE.pdf",
  tagsx:"antioxidante emagrecimento emagrecer saúde metabolismo energia",
  },
  {
    nome: "Resveratrol",
    foto: "https://cdn.shopify.com/s/files/1/0469/4500/9826/files/trans_resveratrol_como_usar_2.jpg?v=1690461697",
    fotodesc: "foto de uvas",
    nomeCientifico: "3,5,4'-trihidroxiestilbeno (Encontrado em uvas, amendoim, etc.)",
    dose: "A dosagem ideal de resveratrol pode variar dependendo da forma de apresentação (cápsulas, comprimidos) e da condição a ser tratada. Geralmente, a dose diária recomendada é de 250mg a 500mg, dividida em duas ou três doses. É importante consultar um médico ou nutricionista antes de iniciar a suplementação, pois a dosagem adequada pode variar de pessoa para pessoa.",
    descricao: "O resveratrol é um composto polifenólico presente em diversas plantas, sendo mais conhecido por estar presente nas uvas, especialmente nas tintas, e no vinho tinto. Ele possui poderosas propriedades antioxidantes, que ajudam a proteger as células dos danos causados pelos radicais livres, combatendo o envelhecimento precoce e reduzindo o risco de diversas doenças crônicas. Além disso, o resveratrol apresenta propriedades anti-inflamatórias, que podem auxiliar na prevenção de doenças cardiovasculares, neurodegenerativas e até mesmo alguns tipos de câncer.",
    linkk: "https://florien.com.br/wp-content/uploads/2017/06/RESVERATROL.pdf",
    tagsx: "Antioxidante Cérebro Envelhecimento coração Anti-inflamatório",
  },
  {
    nome: "Equinácea",
    foto: "https://upload.wikimedia.org/wikipedia/commons/3/3b/Echinacea_purpurea_001.JPG",
    fotodesc: "foto de flores de equinácea",
    nomeCientifico: "Echinacea purpurea",
    dose: "A dose recomendada de equinácea pode variar dependendo da forma de apresentação (chá, cápsulas, tintura) e da condição a ser tratada. Geralmente, a dose diária recomendada é de 300 a 900 mg de extrato seco da planta. É importante consultar um médico ou profissional de saúde antes de iniciar o uso, especialmente se você estiver grávida, amamentando ou tomando outros medicamentos.",
    descricao: "A equinácea, uma planta medicinal nativa da América do Norte, é amplamente conhecida por suas propriedades imunomoduladoras. Rica em compostos ativos como alcamidas e polissacarídeos, ela estimula a produção de células de defesa do organismo, auxiliando na prevenção e no tratamento de infecções respiratórias como gripes e resfriados. Além disso, a equinácea possui ação anti-inflamatória e antioxidante, ajudando a reduzir os sintomas de doenças respiratórias e a fortalecer o sistema imunológico de forma geral. Seu uso tradicional se estende também para o tratamento de feridas, queimaduras e inflamações da pele.",
    linkk: "https://florien.com.br/wp-content/uploads/2016/06/EQUINACEA-PURPUREA.pdf",
    tagsx:"imunidade gripe saúde inverno bem-estar equinacea",
  },
  {
    nome: "Ginkgo Biloba",
    foto: "https://c.files.bbci.co.uk/12FF3/production/_110511877_gettyimages-1127082515.jpg",
    fotodesc: "foto de árvores de ginkgo biloba",
    nomeCientifico: "Ginkgo biloba",
    dose: "A dosagem recomendada de Ginkgo biloba pode variar dependendo do produto e da condição a ser tratada. Geralmente, a dose diária recomendada é de 80 a 240 mg de extrato seco da planta, dividida em duas ou três doses. É importante consultar um médico ou nutricionista antes de iniciar a suplementação, pois a dosagem adequada pode variar de pessoa para pessoa.",
    descricao: "O Ginkgo biloba, uma árvore milenar, tem sido utilizado na medicina tradicional chinesa há séculos. Seus extratos são ricos em flavonoides e terpenóides, substâncias com poderosas propriedades antioxidantes e anti-inflamatórias. Essas propriedades conferem ao Ginkgo biloba diversos benefícios para a saúde, como melhora da circulação sanguínea, especialmente no cérebro, o que pode auxiliar na prevenção de doenças neurodegenerativas como o Alzheimer e a demência. Além disso, o Ginkgo biloba pode ajudar a melhorar a memória, a concentração e a função cognitiva, além de proteger as células contra os danos causados pelos radicais livres.",
    linkk: "",
    tagsx:"memória concentração circulação cérebro saúde",
  },
  {
    nome: "Maconha",
    foto: "https://s2-g1.glbimg.com/iji3jGfD_7nEM9ZdMQBwFB-Jgv4=/0x0:1280x960/984x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2018/A/Z/uB5sV8R5WBOP09GMuYEQ/maconha1.jpg",
    fotodesc: "foto das folhas da maconha",
    nomeCientifico: "Cannabis sativa",
    dose: "A dosagem e a posologia da maconha medicinal variam conforme a condição a ser tratada e a resposta individual do paciente. É fundamental iniciar com doses baixas e ajustar gradualmente, sob orientação médica. O uso pode ser feito via fumar, vaporizar, ou consumir em forma de óleos e cápsulas, sempre respeitando as recomendações de um profissional de saúde.",
    descricao: "A maconha, ou Cannabis sativa, oferece diversas funções medicinais. Seu principal composto, o THC, proporciona alívio da dor crônica e reduz náuseas, sendo útil no tratamento de câncer e outras condições. O CBD, outro componente, atua como anti-inflamatório, ansiolítico e anticonvulsivante. A planta também pode estimular o apetite e ajudar em distúrbios neurológicos como epilepsia e esclerose múltipla. Seu uso terapêutico deve ser supervisionado por profissionais de saúde para dosagem e eficácia adequadas.",
    linkk: "https://www.uniad.org.br/wp-content/uploads/dlm_uploads/2019/10/A_Trag%C3%A9dia_da_Maconha_causas_consequ%C3%AAncias_e_preven%C3%A7%C3%A3o.pdf",
    tagsx:"canabis verdinha ansiedade ",
  },
  {
    nome: "Alecrim",
    foto: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSuyuWrvBZtEEUdjumMLyUYBza5C9B9W14AnQ&s",
    fotodesc: "foto das folhas de alecrim",
    nomeCientifico: "Rosmarinus officinalis",
    dose: "A dose recomendada de alecrim pode variar conforme a forma de uso. Geralmente, para infusões, utiliza-se 1 a 2 colheres de chá de folhas secas para cada xícara de água fervente, de 1 a 3 vezes ao dia. Para extratos ou óleos essenciais, seguir as orientações do fabricante e consultar um profissional de saúde antes do uso, especialmente se você estiver grávida, amamentando ou em tratamento com outros medicamentos.",
    descricao: "O alecrim, conhecido cientificamente como Rosmarinus officinalis, é uma erva aromática popular na culinária e na medicina tradicional. Possui propriedades antioxidantes e anti-inflamatórias, podendo auxiliar na digestão, melhorar a circulação e aliviar dores musculares. Além disso, o alecrim é conhecido por seu efeito estimulante e potencial de melhorar a memória e a concentração. É amplamente utilizado em forma de chá, óleos essenciais e temperos.",
    linkk: "hhttps://florien.com.br/wp-content/uploads/2016/06/ALECRIM-2.pdf",
    tagsx: "alecrim erva digestão circulação memória anti-inflamatório antioxidante",
  },
  {
    nome: "Sucupira",
    foto: "https://image.tuasaude.com/media/article/zc/px/sucupira_399_l.jpg",
    nomeCientifico: "Pterodon emarginatus",
    dose: "A dose de sucupira pode variar conforme a forma de administração. Para pó ou cápsulas, a dose comum é de 500mg a 1g por dia, dividida em duas ou três doses. Para preparações em chá, utiliza-se 1 a 2 colheres de chá das sementes trituradas para cada xícara de água fervente. Sempre consulte um profissional de saúde antes de iniciar o uso, especialmente se estiver grávida, amamentando ou em tratamento com outros medicamentos.",
    descricao: "A sucupira, cientificamente conhecida como Pterodon emarginatus, é uma planta medicinal amplamente utilizada na medicina tradicional brasileira. É conhecida por suas propriedades anti-inflamatórias e analgésicas, frequentemente utilizada para tratar dores articulares e problemas de artrite. Além disso, a sucupira pode ter efeitos positivos sobre o sistema imunológico e auxiliar na recuperação de lesões. Seu uso deve ser supervisionado por um profissional de saúde para garantir a dose e a eficácia adequadas.",
    linkk: "https://florien.com.br/wp-content/uploads/2016/06/SUCUPIRA.pdf",
    tagsx: "sucupira artrite inflamação dor articular saúde imunidade",
  },
];